### ISSUE TITLE
[기능] 알람을 제공

### ISSUE THREAD

**Issue by alertjjm** [dnd-side-project/dnd-5th-5-backend#105]
- [ ] 알람 API가 무엇을 제공할 것인가?: imgUrl, Category, 시간, 문장("~~님이 친구가 되고 싶어합니다"), 볼드처리할 문자열들, 리다이렉트링크?
- [ ] 사용자별로 알람들을 DB에 저장. 사용자가 삭제도 할 수 있게(Async로..?)

**Comment by alertjjm** [comment]
![image](https://user-images.githubusercontent.com/46064193/128512667-44b1a8da-ffe4-48e7-815f-a5de7fe5f130.png)

**Comment by alertjjm** [comment]
@Catnap421 여기에 Alarm 도메인에 enum으로 category(알람종류 string으로), 알람에 표시할 이미지 imgURL, 리다이렉트 URL 필드 더 추가하면 좋지않을까?

![image](https://user-images.githubusercontent.com/46064193/128513266-78e10ea6-28bd-4344-a492-03b457c99932.png)

**Comment by Catnap421** [comment]
@alertjjm enum은 좋은 생각같아!
만약 친구 이미지가 바뀌면 바뀐걸로 보여줘야 할 것 같아서 이미지 URL은 친구 엔티티랑 참조관계로 가져오려고 했어! 
리다이렉트 URL은 NOTICE_ALARM 엔티티에 추가하면 좋겠다
