### ISSUE TITLE
[인프라] 몽고 DB 설정

### ISSUE THREAD

**Issue by Catnap421** [dnd-side-project/dnd-5th-5-backend#11]
- [x] 몽고 atlas 연결
- [x] secret 방법 모색
- [x] 임베디드 몽고 설치

**Comment by alertjjm** [comment]
secret은 Vault나 Github Secret이런거로 알아봐주라 
1. application properties에는 $USERNAME, $PASSWORD으로 적고, 환경변수를 secret으로 해서 끼워넣는 방법도 있고
2. Vault로 secret을 끼워넣는거도 있고
