### ISSUE TITLE
[토론] 친구 정보 엔티티 변경

### ISSUE THREAD

**Issue by Catnap421** [dnd-side-project/dnd-5th-5-backend#122]
@alertjjm 
현재 친구 정보 엔티티에는 다음과 같은 프로퍼티를 지님
- 사용자id
- 친구 리스트
- 보류 리스트(보류 리스트는 나의 수락을 보류 중인 리스트를 표현함)

하지만 친구와의 관계를 생각해 보았을 때, 친구 신청을 하고 보류 중인 경우(친구 수락 보류)가 존재하며, 지금의 엔티티로는 이 상태를 파악하기 위해선 상대방의 보류 리스트를 탐색해야 함

자신의 친구 상태를 파악하는 데, 상대방의 친구 상태를 가져와서 계산하는 게 이상하다고 판단됨

그래서 보류 리스트를
- 친구의 수락 보류 리스트(friendAcceptancePending)
- 나의 수락 보류 리스트(MyAcceptancePending)

두 가지로 분리할까 생각 중인데 어때?

**Comment by alertjjm** [comment]
앗 내가 이해하고있었던 pendings랑은 좀 다르긴하다
내가생각했던건
A가 B한테 친구신청을 했어
그러면 B.friendInfo.pendings.add(A.memberId)
이거로 생각을 하고 있었는데 지금 설계는 반대라는 말이구나?

**Comment by Catnap421** [comment]
아냐 지금이 그렇게 하고 있어!
즉 B입장에선 나의 수락을 보류 중인 리스트니까!

**Comment by alertjjm** [comment]
아하 두개 만들어도 좋을거같아! 친구 상태(친구임, 아님, 보류중임) 파악할때 너 말대로 상대방의 pendings를 찾는거보단 내꺼 보고 찾는게 맞는거 같아
대신에 그러면 두개로 나뉘면서 트랜잭션 처리할때 주의해줘야할거같아
