### ISSUE TITLE
[2차 기능] 알람 기능

### ISSUE THREAD

**Issue by alertjjm** [dnd-side-project/dnd-5th-5-backend#128]
- 알람기능은 완성
- 친구신청, 수락, 거절 등의 기능도 완성

친구 신청 시에 이벤트, aop를 적용해서 async로 알람을 발행하는 기능을 추가해야 함

토론사항
1) 친구를 거절, 수락했을 때 알람에서 그 내용을 삭제할 것인지
2) 거절, 수락 둘다 삭제할 것인지 (어떤경우에서 삭제할 것인지)
@Catnap421

**Comment by Catnap421** [comment]
알람기능은 프론트랑도 이야기를 해봐야 할 것 같아! 새로운 알림이 왔을 때, 새로운 메시지가 도착했다는 걸 알리기 위해선 메시징 처리를 해야하는데, 그럴려면 프론트랑 백 모두 메시징 플랫폼을 사용해야하지 않을까 생각했어. 그래서 파이어베이스 메시징 기능을 원래는 사용할까 했는데.. 지금은 프론트 부담이 많으니까 다른 기능 먼저 구현하는 게 어때?

**Comment by alertjjm** [comment]
아하 처음에는 그냥 매번 마이페이지 새로고침할때 getAlarms로 가져오거나 js로 계속 불러오면서 업데이트할 줄 알았는데 메시징 처리로 하는게 맞겠네
그래그래 다른거부터 먼저하는게 낫겠다

**Comment by Catnap421** [comment]
알라 카드 획득 및 알라 카드 완성 또한 알림을 주도록 하기!
