### ISSUE TITLE
[보완] 사용자 접근 제어

### ISSUE THREAD

**Issue by alertjjm** [dnd-side-project/dnd-5th-5-backend#132]
- 8월 9일 회의때 나온 내용
- 프론트와 백엔드 협의해서 허용되지 않은 사용자의 경우에 어떻게 접근제어를 할 것인지 논의하기

종민 생각 - 백엔드에서 인증이 필요한 API 경우는 @CurrentUser로 jwt토큰을 받도록 하였고,  invalid한 jwt토큰이 넘어오거나 jwt토큰이 없는 경우는 애초에 500에러가 뜨면서 사용이 불가능함. 그래서 추가적으로 백엔드에서 접근제어를 구현할 부분은 없는 것 같고(굳이 하자면 CORS를 프론트엔드의 IP만 가능하도록하는거..?) 지금 상태로도 백은 접근제어가 되고있다고 생각하는데

@Catnap421 혹시 어떤 부분에서 이런게 필요할지 알려줄 수 있으??

**Comment by Catnap421** [comment]
이건 진짜 내가 웹이랑은 작업을 안해봐서 잘 모르는 영역이라 남긴거였고, 없다고 생각하면 지워도 돼!

**Comment by alertjjm** [comment]
아하 오케오케 일단 혹시모르니까 일단 남겨놓긴할게

**Comment by Catnap421** [comment]
따로 discussion이란 탭이 존재해서 이슈는 닫도록 하겠음
