### ISSUE TITLE
[인프라] 개발 서버 및 운영 서버 분리

### ISSUE THREAD

**Issue by Catnap421** [dnd-side-project/dnd-5th-5-backend#174]
운영 서버에선 무중단 배포가 가능해야함

**Comment by alertjjm** [comment]
@Catnap421 서버 자체는 분리완료. 지금 develop으로 배포되면 서버 두군데서 동시에 뜨게 되는데, 나중에 찐 배포시에만 조건을 main, develop으로 분리하면 됨

서버에서는 스크립트 수정해서 따로 두번씩 안올려줘도 이제 5초정도 내려갔다가 올라오기도하고, 정기배포는 자주 해야 1주일에 한번 하니까 완전한 무중단을 당장은 꼭 안해도될 것 같은데 혹시 무중단 배포 환경 마련 되면 그때 main 브랜치쪽은 옮겨도댐!

**Comment by alertjjm** [comment]
+) 몽고디비 아틀라스도 하나 더 만들어서 개발용으로 연결해줘야할거같아
