### ISSUE TITLE
[설정] 필요한 라이브러리 설치

### ISSUE THREAD

**Issue by Catnap421** [dnd-side-project/dnd-5th-5-backend#2]
## 할 일

필요한 라이브러리를 설치한다.

1. MapStruct
2. DBunit (nosql은 지원하지 않기 때문에, DataMongoTest같은 다른 방법 적용해야 할 듯?)
3. MongoDB - (추후에 데이터 정해지면 AWS로 마이그레이션)
 - mongoDB로 하게 될 경우, embedded Mongo 설치하기

**Comment by alertjjm** [comment]
3. dynamo db는 gradle import하는 라이브러리가 몽고디비랑 다르게 있어서 몽고디비 일부러 gradle에서 뺐는데 몽고디비 쓸거야? 다이나모 디비 쓸지 몽고디비 결정 해야될듯! 왜냐면 둘다 nosql 이긴한데 몽고디비는 스키마를 안짜도 되고 dynamo db는 스키마를 고정적으로 짜야된다는 차이가 있대! 만약 mongodb쓸거면 클라우드 인스턴스에 도커로 몽고디비 올려서 해야될거같은데 어떤거같아?

https://kuimoani.tistory.com/entry/DynamoDB-%EB%8C%80%EC%8B%A0-MongoDB%EB%A5%BC-%EC%8D%A8%EC%95%BC-%ED%95%98%EB%8A%94-7%EA%B0%80%EC%A7%80-%EC%9D%B4%EC%9C%A0

https://interconnection.tistory.com/61

**Comment by Catnap421** [comment]
음 아니면 bob에 서버 얻을 수 있긴한데, 한 번 서버 얻어서 거기에 도커로 몽고db 띄워볼게! dynamoDB로 섣불리 정하기엔 돈이 생각보다 들 것 같네

**Comment by alertjjm** [comment]
응응 좋아!! 월욜날 회의해서 기능 한번 다시 보고 도메인 어케 짤지 얘기해보자

**Comment by Catnap421** [comment]
1. 임베디드 몽고 - 대표적, 하지만 무거움(코드로 미리 그 테스트 환경세팅을 한다, 코드로 테스트 이후에 변화를 확인을 해야한다.)
2. 몽고유닛 - 최신, 가벼움(json 파일을 통해사, 환경세팅 및 변화에 대해 확인을 한다.)
