### ISSUE TITLE
[기능] 사용자 닉네임 중복 처리 엔드포인트

### ISSUE THREAD

**Issue by Catnap421** [dnd-side-project/dnd-5th-5-backend#24]
- 사용자의 닉네임에 대해 중복 여부를 알려줘야 한다.

**Comment by alertjjm** [comment]
@Catnap421 이거 GET으로 쿼리스트링으로 받는게 맞을까 POST로 받는게 맞을까?
저거로 보면 GET으로 하고 쿼리스트링으로 물어보는게 맞아보이긴하는데 

![image](https://user-images.githubusercontent.com/46064193/126476157-b1a69295-7444-4a02-80a0-45528d95b16c.png)

**Comment by Catnap421** [comment]
응응 나도 GET이랑 쿼리스트링이 좋아보여!
api/v1/member?nickname=OOO
아니면 
api/v1/member/exist?nickname=OO
