### ISSUE TITLE
[수정] 기본 닉네임 변경

### ISSUE THREAD

**Issue by Catnap421** [dnd-side-project/dnd-5th-5-backend#54]
https://github.com/dnd-side-project/dnd-5th-5-backend/blob/e8f209c9f10d785ed9c4886e86af97ff054a1111/src/main/java/com/meme/ala/domain/member/service/MemberServiceImpl.java#L64

ala_숫자로 변경할 것

**Comment by alertjjm** [comment]
확인! 24일 할 예정
