### ISSUE TITLE
[보완] 사용자 회원 가입 시, 친구 엔티티 저장하기

### ISSUE THREAD

**Issue by Catnap421** [dnd-side-project/dnd-5th-5-backend#69]
사용자 회원 가입 시, 해당 사용자의 id를 갖는 친구 엔티티를 저장해야 한다.

**Comment by alertjjm** [comment]
오홍 굳굳 이거 필요하네 나도 initAggreation()으로 하나 만들어서 join에 끼워넣었거든? 그거처럼 서비스에서 메소드 하나만들어서 join에 끼워넣으면되겠다. 컨벤션맞추는 용도로 이거 한번 확인해보는거도 좋을거같아! 이거에 맞춰도되고 너가 더 좋은 방법있으면 너가 먼저해주고 이슈올려주면 내가 너꺼에 맞춰서 initAggregation 수정하구
![image](https://user-images.githubusercontent.com/46064193/127464022-34bf98b9-5482-462c-a283-907d6e474242.png)
@Catnap421

**Comment by Catnap421** [comment]
[jpa commit 시점](https://ict-nroo.tistory.com/130)에 따라 memberId를 얻으려면 Transaction의 Commit이 완료된 이후에 initFriendInfo를 호출해야 함. FriendInfo의 초기화의 경우, 비동기로 처리해도 되기 때문에  `@TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)` 의 이벤트 리스너를 활용해서 처리할 예정
