### ISSUE TITLE
[기능] 카드세팅정보(배경이미지, 폰트, 폰트색) 저장소에 저장 후 관리, 제공

### ISSUE THREAD

**Issue by alertjjm** [dnd-side-project/dnd-5th-5-backend#80]
- [x] s3, 웹저장소 등 적절한 저장 방법 알아보기
- [x] 디자인팀에서 제공한 카드세팅정보 저장해놓기
- [x] 이미지: URL, 폰트: noto sans (String), 폰트색: #FFFFFF혹은 FFFFFF (String)으로 제공

**Comment by alertjjm** [comment]
@Catnap421 
https://gaemi606.tistory.com/entry/Spring-Boot-S3-%ED%8C%8C%EC%9D%BC-%EC%97%85%EB%A1%9C%EB%93%9C
흠 이거보니까 s3로 저장 후 URL 받아오는거 있어서 S3쓰면 될거같은데
여기서도 secret이 문제당 월욜날 둘이서 https://github.com/dnd-side-project/dnd-5th-5-backend/issues/21 이거 해결방법 생각해봐야할거같아!

**Comment by Catnap421** [comment]
https://app.zeplin.io/project/60fed4b0462b5b10a8599f47/styleguide/textstyles?seid=610012ce77b8d11848138104
내가 정리해서 이미지 폰트 정보 올려야겠다
